language: haskell

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

jobs:
  include:
  - ghc: 8.10.3

  - ghc: 8.10.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - |
    if [ -z "$STACK_YAML" ]; then
      cabal update
      cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
      cabal build all
    else
      curl -sSL https://get.haskellstack.org/ | sh
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --ghc-options=-Werror
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal test all
    else
      stack test --system-ghc
    fi

notifications:
  email: false
